# Generated by Django 3.0.4 on 2020-03-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='dev_name',
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='', max_length=15),
        ),
    ]
